"""
Ručno kuriran rečnik i fraze za svaku lekciju face2face Elementary 2nd ed.
Izvor: prvi zadaci u svakoj lekciji (Vocabulary box) i Real World/HELP WITH GRAMMAR primeri.
Format po lekciji:
  - vocab: lista parova {"en": "...", "sr": "..."} — reči/sintagme za učenje
  - phrases: lista parova {"en": "...", "sr": "..."} — funkcionalne fraze i primeri
  - grammar: opcionalna lista parova {"en": "...", "sr": "..."} sa gramatičkim primerima
"""

from __future__ import annotations

LESSONS_VOCAB: dict[str, dict[str, list[dict[str, str]]]] = {
    # =================================================================
    # UNIT 1
    # =================================================================
    "1a": {
        "vocab": [
            {"en": "Brazil → Brazilian", "sr": "Brazil → Brazilac/Brazilka"},
            {"en": "Australia → Australian", "sr": "Australija → Australijanac/-ka"},
            {"en": "Argentina → Argentinian", "sr": "Argentina → Argentinac/-ka"},
            {"en": "the USA → American", "sr": "SAD → Amerikanac/-ka"},
            {"en": "Germany → German", "sr": "Nemačka → Nemac/Nemica"},
            {"en": "Italy → Italian", "sr": "Italija → Italijan/-ka"},
            {"en": "Mexico → Mexican", "sr": "Meksiko → Meksikanac/-ka"},
            {"en": "Russia → Russian", "sr": "Rusija → Rus/Ruskinja"},
            {"en": "Egypt → Egyptian", "sr": "Egipat → Egipćan/-ka"},
            {"en": "the UK → British", "sr": "Velika Britanija → Britanac/-ka"},
            {"en": "Spain → Spanish", "sr": "Španija → Španac/Špankinja"},
            {"en": "Poland → Polish", "sr": "Poljska → Poljak/Poljakinja"},
            {"en": "Turkey → Turkish", "sr": "Turska → Turčin/Turkinja"},
            {"en": "China → Chinese", "sr": "Kina → Kinez/Kineskinja"},
            {"en": "Japan → Japanese", "sr": "Japan → Japanac/Japanka"},
            {"en": "France → French", "sr": "Francuska → Francuz/Francuskinja"},
        ],
        "phrases": [
            {"en": "Hello. / Hi.", "sr": "Zdravo. / Ćao."},
            {"en": "How are you?", "sr": "Kako si?"},
            {"en": "I'm fine, thanks. And you?", "sr": "Dobro sam, hvala. A ti?"},
            {"en": "I'm OK, thanks.", "sr": "Solidno, hvala."},
            {"en": "Nice to meet you. — You too.", "sr": "Drago mi je. — I meni."},
            {"en": "What's your name, please?", "sr": "Kako se zovete, molim vas?"},
            {"en": "It's Carlos Moreno.", "sr": "Ja sam Karlos Moreno."},
            {"en": "Where are you from?", "sr": "Odakle si?"},
            {"en": "I'm from Colombia.", "sr": "Iz Kolumbije sam."},
            {"en": "What's your nationality?", "sr": "Koje si nacionalnosti?"},
            {"en": "I'm Korean.", "sr": "Korejac/Korejka sam."},
            {"en": "Bianca, this is Toshi.", "sr": "Bjanka, ovo je Toši. (predstavljanje)"},
        ],
        "grammar": [
            {"en": "I'm from Spain.", "sr": "Iz Španije sam."},
            {"en": "You're a teacher.", "sr": "Ti si nastavnik."},
            {"en": "He's from Italy. / She's from Brazil.", "sr": "On/Ona je iz Italije/Brazila."},
            {"en": "We're students.", "sr": "Mi smo studenti."},
            {"en": "They're British.", "sr": "Oni/One su Britanci."},
            {"en": "Where's he from?", "sr": "Odakle je on?"},
            {"en": "What's your name?", "sr": "Kako se zoveš?"},
            {"en": "my, your, his, her, our, their", "sr": "moj, tvoj, njegov, njen, naš, njihov"},
        ],
    },
    "1b": {
        "vocab": [
            {"en": "a manager", "sr": "menadžer"},
            {"en": "a doctor", "sr": "lekar"},
            {"en": "an engineer", "sr": "inženjer"},
            {"en": "a sales assistant", "sr": "prodavac (u radnji)"},
            {"en": "a waiter / a waitress", "sr": "konobar / konobarica"},
            {"en": "a cleaner", "sr": "čistač(ica)"},
            {"en": "a police officer", "sr": "policajac"},
            {"en": "an actor / an actress", "sr": "glumac / glumica"},
            {"en": "a musician", "sr": "muzičar"},
            {"en": "a teacher", "sr": "nastavnik/profesor"},
            {"en": "a student", "sr": "student/učenik"},
            {"en": "a housewife", "sr": "domaćica"},
            {"en": "an accountant", "sr": "računovođa"},
            {"en": "a lawyer", "sr": "advokat"},
            {"en": "a builder", "sr": "građevinar"},
            {"en": "a mechanic", "sr": "mehaničar"},
            {"en": "I'm unemployed.", "sr": "Nezaposlen/-a sam."},
            {"en": "I'm retired.", "sr": "U penziji sam."},
        ],
        "phrases": [
            {"en": "What's your job?", "sr": "Šta radiš (zanimanje)?"},
            {"en": "What do you do?", "sr": "Čime se baviš?"},
            {"en": "I'm a manager.", "sr": "Ja sam menadžer."},
            {"en": "What's his/her job?", "sr": "Šta on/ona radi?"},
            {"en": "He's a mechanic.", "sr": "On je mehaničar."},
            {"en": "She's an actress.", "sr": "Ona je glumica."},
            {"en": "Are you from Spain?", "sr": "Da li si iz Španije?"},
            {"en": "Yes, I am. / No, I'm not.", "sr": "Da, jesam. / Ne, nisam."},
            {"en": "Is she a musician?", "sr": "Da li je ona muzičarka?"},
            {"en": "Yes, she is. / No, she isn't.", "sr": "Da, jeste. / Ne, nije."},
        ],
        "grammar": [
            {"en": "I'm not a teacher.", "sr": "Nisam nastavnik."},
            {"en": "We aren't from the USA.", "sr": "Nismo iz Amerike."},
            {"en": "He isn't famous.", "sr": "On nije poznat."},
            {"en": "a doctor (consonant) / an engineer (vowel)", "sr": "a + suglasnik / an + samoglasnik"},
        ],
    },
    "1c": {
        "vocab": [
            {"en": "twenty (20)", "sr": "dvadeset"},
            {"en": "thirty (30)", "sr": "trideset"},
            {"en": "forty (40)", "sr": "četrdeset"},
            {"en": "fifty (50)", "sr": "pedeset"},
            {"en": "sixty (60)", "sr": "šezdeset"},
            {"en": "seventy (70)", "sr": "sedamdeset"},
            {"en": "eighty (80)", "sr": "osamdeset"},
            {"en": "ninety (90)", "sr": "devedeset"},
            {"en": "a hundred (100)", "sr": "sto"},
            {"en": "first name", "sr": "ime"},
            {"en": "surname", "sr": "prezime"},
            {"en": "home number", "sr": "kućni broj telefona"},
            {"en": "work number", "sr": "broj na poslu"},
            {"en": "mobile number", "sr": "broj mobilnog"},
            {"en": "home address", "sr": "kućna adresa"},
            {"en": "email address", "sr": "imejl adresa"},
            {"en": "postcode", "sr": "poštanski broj"},
            {"en": "credit card number", "sr": "broj kreditne kartice"},
            {"en": "a credit card", "sr": "kreditna kartica"},
            {"en": "a business card", "sr": "vizit-karta"},
            {"en": "a mobile phone", "sr": "mobilni telefon"},
        ],
        "phrases": [
            {"en": "What's your first name/surname?", "sr": "Kako ti je ime/prezime?"},
            {"en": "What's your phone number?", "sr": "Koji ti je broj telefona?"},
            {"en": "It's 020 7946 0322.", "sr": "(0 = oh; 11 = double one)"},
            {"en": "What's your email address?", "sr": "Koja ti je imejl adresa?"},
            {"en": "How do you spell that?", "sr": "Kako se to piše?"},
            {"en": "Sorry?", "sr": "Izvini? (nisam čuo/la)"},
            {"en": "Could you say that again, please?", "sr": "Možeš li ponoviti, molim te?"},
            {"en": "Could you repeat that, please?", "sr": "Možeš li to da ponoviš?"},
            {"en": "Pardon?", "sr": "Molim? (nisam razumeo/la)"},
        ],
        "grammar": [
            {"en": "thirteen vs. thirty (stress matters)", "sr": "13 i 30 — drugačiji naglasak"},
            {"en": "fourteen vs. forty", "sr": "14 i 40 — drugačiji naglasak"},
            {"en": "fifty-eight, fifty-nine, sixty…", "sr": "58, 59, 60 — sa crticom"},
        ],
    },
    "1d": {
        "vocab": [
            {"en": "a wallet", "sr": "novčanik"},
            {"en": "a diary", "sr": "dnevnik/rokovnik"},
            {"en": "an MP3 player", "sr": "MP3 plejer"},
            {"en": "a mobile / a mobile phone", "sr": "mobilni telefon"},
            {"en": "a watch", "sr": "ručni sat"},
            {"en": "an umbrella", "sr": "kišobran"},
            {"en": "a bag", "sr": "torba"},
            {"en": "shoes", "sr": "cipele"},
            {"en": "a camera", "sr": "fotoaparat"},
            {"en": "a coat", "sr": "kaput"},
            {"en": "a bike / a bicycle", "sr": "bicikl"},
            {"en": "a radio", "sr": "radio"},
            {"en": "a suitcase", "sr": "kofer"},
            {"en": "a laptop", "sr": "laptop"},
            {"en": "a dress", "sr": "haljina"},
            {"en": "an ID card", "sr": "lična karta"},
            {"en": "false teeth", "sr": "veštačka vilica/zubi"},
        ],
        "phrases": [
            {"en": "What's this/that in English?", "sr": "Kako se ovo/to kaže na engleskom?"},
            {"en": "It's a poster.", "sr": "To je poster."},
            {"en": "What are these/those in English?", "sr": "Kako se ovi/oni zovu na engleskom?"},
            {"en": "They're keys.", "sr": "To su ključevi."},
            {"en": "Whose phone is this?", "sr": "Čiji je ovo telefon?"},
            {"en": "It's mine. / It's hers.", "sr": "Moj je. / Njen je."},
        ],
        "grammar": [
            {"en": "a bag → bags", "sr": "torba → torbe (-s)"},
            {"en": "a watch → watches; a dress → dresses", "sr": "-ch/-ss → +es"},
            {"en": "a diary → diaries", "sr": "y posle suglasnika → -ies"},
            {"en": "a man → men", "sr": "muškarac → muškarci"},
            {"en": "a woman → women", "sr": "žena → žene"},
            {"en": "a child → children", "sr": "dete → deca"},
            {"en": "a person → people", "sr": "osoba → ljudi"},
            {"en": "a tooth → teeth", "sr": "zub → zubi"},
            {"en": "this/that (singular), these/those (plural)", "sr": "ovaj/onaj — ovi/oni"},
        ],
    },
    # =================================================================
    # UNIT 2
    # =================================================================
    "2a": {
        "vocab": [
            {"en": "new ↔ old", "sr": "nov ↔ star"},
            {"en": "big ↔ small", "sr": "veliki ↔ mali"},
            {"en": "good ↔ bad", "sr": "dobar ↔ loš"},
            {"en": "early ↔ late", "sr": "rano ↔ kasno"},
            {"en": "cheap ↔ expensive", "sr": "jeftin ↔ skup"},
            {"en": "fast ↔ slow", "sr": "brz ↔ spor"},
            {"en": "beautiful ↔ ugly", "sr": "lep ↔ ružan"},
            {"en": "young ↔ old", "sr": "mlad ↔ star"},
            {"en": "easy ↔ difficult", "sr": "lak ↔ težak"},
            {"en": "right ↔ wrong", "sr": "tačan ↔ pogrešan"},
            {"en": "nice", "sr": "lep, prijatan"},
            {"en": "great", "sr": "sjajan"},
            {"en": "important", "sr": "važan"},
            {"en": "favourite", "sr": "omiljeni"},
        ],
        "phrases": [
            {"en": "She's late.", "sr": "Kasni."},
            {"en": "It's a small bag.", "sr": "To je mala torba."},
            {"en": "It's a very difficult question.", "sr": "Vrlo je teško pitanje."},
            {"en": "Those are my new shoes.", "sr": "Ovo su moje nove cipele."},
            {"en": "I love football.", "sr": "Volim fudbal."},
        ],
        "grammar": [
            {"en": "I've got a car.", "sr": "Imam auto."},
            {"en": "He's got a laptop. / She's got a phone.", "sr": "On/Ona ima laptop/telefon."},
            {"en": "I haven't got a TV.", "sr": "Nemam TV."},
            {"en": "He hasn't got a car.", "sr": "On nema auto."},
            {"en": "Have you got a pen? — Yes, I have. / No, I haven't.", "sr": "Imaš li olovku? — Da. / Ne."},
            {"en": "Has she got a car? — Yes, she has. / No, she hasn't.", "sr": "Ima li ona auto? — Da. / Ne."},
        ],
    },
    "2b": {
        "vocab": [
            {"en": "father / dad", "sr": "otac / tata"},
            {"en": "mother / mum", "sr": "majka / mama"},
            {"en": "parents", "sr": "roditelji"},
            {"en": "husband", "sr": "muž"},
            {"en": "wife", "sr": "žena (supruga)"},
            {"en": "son", "sr": "sin"},
            {"en": "daughter", "sr": "ćerka"},
            {"en": "children / kids", "sr": "deca"},
            {"en": "brother", "sr": "brat"},
            {"en": "sister", "sr": "sestra"},
            {"en": "grandfather / granddad", "sr": "deda"},
            {"en": "grandmother / grandma", "sr": "baka"},
            {"en": "grandparents", "sr": "baba i deda"},
            {"en": "grandson", "sr": "unuk"},
            {"en": "granddaughter", "sr": "unuka"},
            {"en": "grandchildren", "sr": "unučad"},
            {"en": "uncle", "sr": "stric/ujak/tetak"},
            {"en": "aunt", "sr": "tetka/strina/ujna"},
            {"en": "cousin", "sr": "rođak/rođaka"},
        ],
        "phrases": [
            {"en": "How many brothers and sisters has Pam got?", "sr": "Koliko Pem ima braće i sestara?"},
            {"en": "How many children have Mary and Ben got?", "sr": "Koliko dece imaju Meri i Ben?"},
            {"en": "Pam is married with two kids.", "sr": "Pem je udata i ima dvoje dece."},
            {"en": "Jill is divorced.", "sr": "Džil je razvedena."},
            {"en": "He's nineteen years old.", "sr": "On ima 19 godina."},
        ],
        "grammar": [
            {"en": "Tom's car (= Tom has a car / Tomov auto)", "sr": "'s = pripadnost (Tomov)"},
            {"en": "Pam's husband", "sr": "Pemin muž"},
            {"en": "my parents' house (plural + ')", "sr": "kuća mojih roditelja"},
            {"en": "He's a doctor. (= is)", "sr": "On je lekar."},
            {"en": "He's got a car. (= has)", "sr": "On ima auto."},
        ],
    },
    "2c": {
        "vocab": [
            {"en": "a second", "sr": "sekunda"},
            {"en": "a minute", "sr": "minut"},
            {"en": "an hour", "sr": "sat"},
            {"en": "a day", "sr": "dan"},
            {"en": "a week", "sr": "nedelja"},
            {"en": "a month", "sr": "mesec"},
            {"en": "a year", "sr": "godina"},
            {"en": "(one) o'clock", "sr": "tačno (jedan sat)"},
            {"en": "quarter past four", "sr": "petnaest do četiri (15 prošlo 4)"},
            {"en": "half past seven", "sr": "pola osam"},
            {"en": "twenty past five", "sr": "pet i dvadeset"},
            {"en": "quarter to ten", "sr": "petnaest do deset"},
            {"en": "twenty to nine", "sr": "dvadeset do devet"},
        ],
        "phrases": [
            {"en": "What time is it?", "sr": "Koliko je sati?"},
            {"en": "What's the time, please?", "sr": "Koliko je sati, molim te?"},
            {"en": "Excuse me, have you got the time, please?", "sr": "Izvinite, imate li tačno vreme?"},
            {"en": "It's 2 o'clock.", "sr": "Dva je sata."},
            {"en": "It's about half past seven.", "sr": "Pola osam je otprilike."},
            {"en": "It's four fifteen.", "sr": "Četiri i petnaest je."},
            {"en": "How much is that?", "sr": "Koliko košta?"},
            {"en": "Two adults, please.", "sr": "Dve odrasle karte, molim."},
            {"en": "Here you are.", "sr": "Izvolite."},
            {"en": "Thanks. — You're welcome.", "sr": "Hvala. — Nema na čemu."},
        ],
        "grammar": [
            {"en": "My class is at ten.", "sr": "Čas mi je u deset."},
            {"en": "It's from 7 to 9:30.", "sr": "Traje od 7 do 9.30."},
            {"en": "£5 = five pounds; €3.50 = three euros fifty", "sr": "izgovaranje cena"},
        ],
    },
    "2d": {
        "vocab": [
            {"en": "a mirror", "sr": "ogledalo"},
            {"en": "a desk", "sr": "radni sto"},
            {"en": "a sofa", "sr": "kauč"},
            {"en": "a carpet", "sr": "tepih"},
            {"en": "a door", "sr": "vrata"},
            {"en": "a bookcase", "sr": "polica za knjige"},
            {"en": "a window", "sr": "prozor"},
            {"en": "the floor", "sr": "pod"},
            {"en": "a plant", "sr": "biljka"},
            {"en": "a coffee table", "sr": "klub-stočić"},
            {"en": "a lamp", "sr": "lampa"},
            {"en": "curtains", "sr": "zavese"},
            {"en": "in", "sr": "u (unutar)"},
            {"en": "on", "sr": "na"},
            {"en": "by / next to", "sr": "pored"},
            {"en": "under", "sr": "ispod"},
            {"en": "behind", "sr": "iza"},
            {"en": "in front of", "sr": "ispred"},
        ],
        "phrases": [
            {"en": "Where's the cat?", "sr": "Gde je mačka?"},
            {"en": "It's under the chair.", "sr": "Ispod stolice je."},
            {"en": "Nick's suitcase is behind the sofa.", "sr": "Nikov kofer je iza kauča."},
            {"en": "His keys are on the desk.", "sr": "Njegovi ključevi su na stolu."},
            {"en": "Whose phone is this? — It's Nick's.", "sr": "Čiji je ovo telefon? — Nikov."},
        ],
    },
    # =================================================================
    # UNIT 3
    # =================================================================
    "3a": {
        "vocab": [
            {"en": "get up", "sr": "ustati (iz kreveta)"},
            {"en": "go to bed", "sr": "ići na spavanje"},
            {"en": "leave home", "sr": "izaći iz kuće"},
            {"en": "get home", "sr": "doći kući"},
            {"en": "have breakfast", "sr": "doručkovati"},
            {"en": "have lunch", "sr": "ručati"},
            {"en": "have dinner", "sr": "večerati"},
            {"en": "start work / classes", "sr": "početi sa poslom / nastavom"},
            {"en": "finish work / classes", "sr": "završiti posao / nastavu"},
            {"en": "sleep", "sr": "spavati"},
            {"en": "live", "sr": "živeti"},
            {"en": "work", "sr": "raditi"},
            {"en": "study", "sr": "učiti/studirati"},
            {"en": "in the morning", "sr": "ujutru"},
            {"en": "in the afternoon", "sr": "popodne"},
            {"en": "in the evening", "sr": "uveče"},
            {"en": "at night", "sr": "noću"},
        ],
        "phrases": [
            {"en": "Where are you from, Kari?", "sr": "Odakle si, Kari?"},
            {"en": "I live and work in Los Angeles.", "sr": "Živim i radim u L.A."},
            {"en": "What time do you get up?", "sr": "U koliko sati ustaješ?"},
            {"en": "I get up at 4.30 in the morning.", "sr": "Ustajem u 4.30 ujutru."},
            {"en": "We start work very early.", "sr": "Vrlo rano počinjemo sa poslom."},
            {"en": "They have an hour for lunch.", "sr": "Imaju sat vremena za ručak."},
        ],
        "grammar": [
            {"en": "I get up at 7. / We start work at 9.", "sr": "Present Simple — bez -s za I/we/they"},
            {"en": "What time do you start?", "sr": "Wh- + do + subj. + glagol"},
            {"en": "Where do they live?", "sr": "Gde oni žive?"},
        ],
    },
    "3b": {
        "vocab": [
            {"en": "stay in", "sr": "ostati kod kuće"},
            {"en": "go out (a lot)", "sr": "često izlaziti"},
            {"en": "eat out", "sr": "jesti napolju (u restoranu)"},
            {"en": "go for a drink", "sr": "otići na piće"},
            {"en": "go to the cinema", "sr": "ići u bioskop"},
            {"en": "go to concerts", "sr": "ići na koncerte"},
            {"en": "go shopping", "sr": "ići u kupovinu"},
            {"en": "phone friends/my family", "sr": "zvati prijatelje/porodicu"},
            {"en": "visit friends/my family", "sr": "posetiti prijatelje/porodicu"},
            {"en": "have coffee with friends", "sr": "popiti kafu sa prijateljima"},
            {"en": "do (a lot of) sport", "sr": "baviti se sportom"},
            {"en": "watch (a lot of) TV/DVDs", "sr": "gledati TV/filmove"},
            {"en": "on Mondays / on Saturday evening", "sr": "ponedeljkom / subotom uveče"},
            {"en": "in the morning / in the day", "sr": "ujutru / preko dana"},
            {"en": "at the weekend / at night", "sr": "vikendom / noću"},
            {"en": "every day / every weekend", "sr": "svakog dana / svakog vikenda"},
        ],
        "phrases": [
            {"en": "Do you go out a lot?", "sr": "Izlaziš li često?"},
            {"en": "Yes, every weekend. / No, never.", "sr": "Da, svakog vikenda. / Ne, nikad."},
            {"en": "I don't watch TV every day.", "sr": "Ne gledam TV svakog dana."},
            {"en": "We don't stay in at the weekend.", "sr": "Ne ostajemo kod kuće vikendom."},
        ],
        "grammar": [
            {"en": "I don't go out on Saturday evening.", "sr": "Ne izlazim subotom uveče."},
            {"en": "You don't work in this office.", "sr": "Ti ne radiš u ovoj kancelariji."},
            {"en": "Do you study English? — Yes, I do. / No, I don't.", "sr": "Učiš li engleski? — Da. / Ne."},
        ],
    },
    "3c": {
        "vocab": [
            {"en": "January / February / March", "sr": "januar / februar / mart"},
            {"en": "April / May / June", "sr": "april / maj / jun"},
            {"en": "July / August / September", "sr": "jul / avgust / septembar"},
            {"en": "October / November / December", "sr": "oktobar / novembar / decembar"},
            {"en": "first (1st)", "sr": "prvi"},
            {"en": "second (2nd)", "sr": "drugi"},
            {"en": "third (3rd)", "sr": "treći"},
            {"en": "fourth (4th)", "sr": "četvrti"},
            {"en": "fifth (5th)", "sr": "peti"},
            {"en": "twelfth (12th)", "sr": "dvanaesti"},
            {"en": "twentieth (20th) / twenty-first (21st)", "sr": "dvadeseti / dvadeset prvi"},
            {"en": "thirtieth (30th) / thirty-first (31st)", "sr": "trideseti / trideset prvi"},
            {"en": "a birthday", "sr": "rođendan"},
            {"en": "a wedding", "sr": "venčanje"},
            {"en": "the birth of a new baby", "sr": "rođenje bebe"},
            {"en": "a New Year's Eve party", "sr": "doček Nove godine"},
            {"en": "a wedding anniversary", "sr": "godišnjica braka"},
        ],
        "phrases": [
            {"en": "Happy birthday!", "sr": "Srećan rođendan!"},
            {"en": "Happy New Year!", "sr": "Srećna Nova godina!"},
            {"en": "Congratulations!", "sr": "Čestitam!"},
            {"en": "Happy anniversary!", "sr": "Srećna godišnjica!"},
            {"en": "What day is it today?", "sr": "Koji je danas dan?"},
            {"en": "What's the date today?", "sr": "Koji je danas datum?"},
            {"en": "When's your birthday?", "sr": "Kada ti je rođendan?"},
            {"en": "It's the fifth of March.", "sr": "Petog marta je."},
            {"en": "It's March the sixth.", "sr": "Šesti je mart."},
            {"en": "It's on June the third.", "sr": "Trećeg juna."},
        ],
    },
    "3d": {
        "vocab": [
            {"en": "always (100%)", "sr": "uvek"},
            {"en": "usually", "sr": "obično"},
            {"en": "often", "sr": "često"},
            {"en": "sometimes", "sr": "ponekad"},
            {"en": "hardly ever", "sr": "skoro nikad"},
            {"en": "never (0%)", "sr": "nikad"},
            {"en": "I → me", "sr": "ja → mene/mi"},
            {"en": "you → you", "sr": "ti → tebe/ti"},
            {"en": "he → him", "sr": "on → njega/mu"},
            {"en": "she → her", "sr": "ona → nju/joj"},
            {"en": "it → it", "sr": "ono → njega"},
            {"en": "we → us", "sr": "mi → nas/nam"},
            {"en": "they → them", "sr": "oni → njih/im"},
        ],
        "phrases": [
            {"en": "I always get up before 9.", "sr": "Uvek ustajem pre 9."},
            {"en": "I sometimes have coffee with them.", "sr": "Ponekad popijem kafu s njima."},
            {"en": "I hardly ever see them.", "sr": "Skoro nikad ih ne viđam."},
            {"en": "He never answers the phone.", "sr": "On nikad ne odgovara na telefon."},
            {"en": "I'm always happy on Mondays.", "sr": "Uvek sam srećan/-na ponedeljkom."},
        ],
        "grammar": [
            {"en": "She is always late. (after BE)", "sr": "Frekvencija ide POSLE be."},
            {"en": "I never watch TV. (before main verb)", "sr": "Frekvencija ide PRE drugog glagola."},
            {"en": "Phone us. / I see them.", "sr": "Object pronouns posle glagola."},
        ],
    },
    # =================================================================
    # UNIT 4
    # =================================================================
    "4a": {
        "vocab": [
            {"en": "take photos", "sr": "fotografisati"},
            {"en": "go to the gym", "sr": "ići u teretanu"},
            {"en": "watch sport on TV", "sr": "gledati sport na TV-u"},
            {"en": "play video games", "sr": "igrati video-igrice"},
            {"en": "play tennis", "sr": "igrati tenis"},
            {"en": "read books or magazines", "sr": "čitati knjige ili časopise"},
            {"en": "go swimming", "sr": "ići na plivanje"},
            {"en": "go running", "sr": "ići na trčanje"},
            {"en": "listen to music", "sr": "slušati muziku"},
            {"en": "go cycling", "sr": "voziti bicikl"},
            {"en": "go clubbing", "sr": "ići u klub"},
            {"en": "listen to the radio", "sr": "slušati radio"},
        ],
        "phrases": [
            {"en": "Do you watch sport on TV?", "sr": "Gledaš li sport na TV?"},
            {"en": "No, never.", "sr": "Ne, nikad."},
            {"en": "Yes, every weekend.", "sr": "Da, svakog vikenda."},
            {"en": "He plays video games.", "sr": "On igra video-igrice."},
            {"en": "He watches lots of DVDs.", "sr": "Gleda mnogo filmova."},
            {"en": "He doesn't like the weather.", "sr": "Ne sviđa mu se vreme."},
            {"en": "She doesn't talk to him very often.", "sr": "Ne priča s njim često."},
            {"en": "He has tennis lessons every week.", "sr": "Ima časove tenisa svake nedelje."},
        ],
        "grammar": [
            {"en": "watch → watches; go → goes; do → does", "sr": "-ch/-sh/-x/-o → +es"},
            {"en": "study → studies", "sr": "y posle suglasnika → -ies"},
            {"en": "have → has (irregular)", "sr": "have ima nepravilno has"},
        ],
    },
    "4b": {
        "vocab": [
            {"en": "travelling", "sr": "putovanje"},
            {"en": "reading", "sr": "čitanje"},
            {"en": "shopping for clothes", "sr": "kupovina garderobe"},
            {"en": "dancing", "sr": "ples"},
            {"en": "cooking", "sr": "kuvanje"},
            {"en": "cats / animals", "sr": "mačke / životinje"},
            {"en": "football", "sr": "fudbal"},
            {"en": "video games", "sr": "video-igrice"},
            {"en": "dance music / rock music / jazz", "sr": "plesna / rok / džez muzika"},
            {"en": "Italian food / Chinese food / fast food", "sr": "italijanska / kineska / brza hrana"},
            {"en": "I love …", "sr": "Obožavam …"},
            {"en": "I really like …", "sr": "Stvarno volim …"},
            {"en": "I quite like …", "sr": "Prilično volim …"},
            {"en": "It's OK.", "sr": "U redu je."},
            {"en": "I don't like …", "sr": "Ne volim …"},
            {"en": "I hate …", "sr": "Mrzim …"},
        ],
        "phrases": [
            {"en": "Do you like dance music?", "sr": "Voliš li plesnu muziku?"},
            {"en": "Yes, I love it. / It's OK. / No, not really.", "sr": "Da, obožavam je. / Solidna je. / Ne baš."},
            {"en": "What does she do in her free time?", "sr": "Šta ona radi u slobodno vreme?"},
            {"en": "Does she watch TV a lot?", "sr": "Da li ona mnogo gleda TV?"},
            {"en": "Yes, she does. / No, she doesn't.", "sr": "Da. / Ne."},
            {"en": "She loves dance music, but she doesn't like rock music.", "sr": "Obožava plesnu muziku, ali ne voli rok."},
        ],
        "grammar": [
            {"en": "I love reading. (verb+ing)", "sr": "Posle love/like/hate ide -ing."},
            {"en": "I enjoy travelling.", "sr": "Volim putovanja."},
            {"en": "What music does she like?", "sr": "Koju muziku voli? (does + bazni glagol)"},
        ],
    },
    "4c": {
        "vocab": [
            {"en": "a margherita pizza", "sr": "pica margerita"},
            {"en": "a burger and chips", "sr": "burger i pomfrit"},
            {"en": "a cheeseburger", "sr": "čizburger"},
            {"en": "a tuna salad", "sr": "salata sa tunjevinom"},
            {"en": "a chicken salad", "sr": "salata sa piletinom"},
            {"en": "an egg mayonnaise sandwich", "sr": "sendvič sa jajetom i majonezom"},
            {"en": "a cheese and tomato sandwich", "sr": "sendvič sa sirom i paradajzom"},
            {"en": "apple pie with cream", "sr": "pita od jabuka sa kremom"},
            {"en": "fruit salad", "sr": "voćna salata"},
            {"en": "ice cream (vanilla / chocolate / strawberry)", "sr": "sladoled (vanila / čokolada / jagoda)"},
            {"en": "red/white wine", "sr": "crveno/belo vino"},
            {"en": "a bottle of beer", "sr": "flaša piva"},
            {"en": "mineral water (still / sparkling)", "sr": "mineralna voda (negazirana / gazirana)"},
            {"en": "tea / coffee", "sr": "čaj / kafa"},
        ],
        "phrases": [
            {"en": "Would you like to order now?", "sr": "Da li želite da naručite?"},
            {"en": "What would you like to drink?", "sr": "Šta biste popili?"},
            {"en": "Would you like a dessert?", "sr": "Želite li dezert?"},
            {"en": "Would you like anything else?", "sr": "Želite li još nešto?"},
            {"en": "Can I have a coffee, please?", "sr": "Mogu li da dobijem kafu, molim?"},
            {"en": "Could I have the bill, please?", "sr": "Mogu li dobiti račun, molim?"},
            {"en": "How much is a tuna salad?", "sr": "Koliko košta salata sa tunjevinom?"},
            {"en": "Twelve pounds twenty-five.", "sr": "Dvanaest funti i 25 penija."},
            {"en": "Yes, please. / No, thanks.", "sr": "Da, molim. / Ne, hvala."},
        ],
    },
    "4d": {
        "vocab": [
            {"en": "biscuits", "sr": "keks"},
            {"en": "milk", "sr": "mleko"},
            {"en": "sugar", "sr": "šećer"},
            {"en": "toast", "sr": "tost"},
            {"en": "bread", "sr": "hleb"},
            {"en": "fish", "sr": "riba"},
            {"en": "eggs", "sr": "jaja"},
            {"en": "an apple", "sr": "jabuka"},
            {"en": "rice", "sr": "pirinač"},
            {"en": "yogurt", "sr": "jogurt"},
            {"en": "coffee / tea", "sr": "kafa / čaj"},
            {"en": "sausages", "sr": "kobasice"},
            {"en": "soup", "sr": "supa"},
            {"en": "cheese", "sr": "sir"},
            {"en": "a banana", "sr": "banana"},
            {"en": "orange juice", "sr": "sok od pomorandže"},
            {"en": "a croissant", "sr": "kroasan"},
            {"en": "jam", "sr": "džem"},
            {"en": "meat", "sr": "meso"},
            {"en": "fruit", "sr": "voće"},
            {"en": "cereal", "sr": "žitarice"},
            {"en": "olives", "sr": "masline"},
            {"en": "tomatoes", "sr": "paradajz"},
            {"en": "vegetables", "sr": "povrće"},
        ],
        "phrases": [
            {"en": "What do you usually have for breakfast?", "sr": "Šta obično jedeš za doručak?"},
            {"en": "I have eggs and toast.", "sr": "Jaja i tost."},
            {"en": "We can count biscuits and apples (countable).", "sr": "Možemo brojati kekse i jabuke (brojivo)."},
            {"en": "We can't count milk and rice (uncountable).", "sr": "Ne možemo brojati mleko i pirinač (nebrojivo)."},
            {"en": "Some milk / some rice", "sr": "nešto mleka / pirinča"},
        ],
        "grammar": [
            {"en": "a/an + singular countable: a banana", "sr": "a/an pred jedninom brojivih"},
            {"en": "(no article) + plural countable / uncountable in general", "sr": "bez člana za uopšteno"},
            {"en": "some + plural / uncountable: some eggs, some milk", "sr": "some za nešto/par"},
        ],
    },
    # =================================================================
    # UNIT 5
    # =================================================================
    "5a": {
        "vocab": [
            {"en": "hot ↔ cold", "sr": "vruć ↔ hladan"},
            {"en": "noisy ↔ quiet", "sr": "bučan ↔ tih"},
            {"en": "well ↔ ill", "sr": "zdrav ↔ bolestan"},
            {"en": "short ↔ tall", "sr": "nizak ↔ visok"},
            {"en": "lucky ↔ unlucky", "sr": "srećan ↔ nesrećan"},
            {"en": "different ↔ the same", "sr": "drugačiji ↔ isti"},
            {"en": "happy ↔ unhappy", "sr": "srećan ↔ nesrećan/tužan"},
            {"en": "boring ↔ interesting", "sr": "dosadan ↔ zanimljiv"},
            {"en": "friendly ↔ unfriendly", "sr": "ljubazan ↔ neljubazan"},
            {"en": "terrible / awful", "sr": "užasan / grozan"},
            {"en": "fantastic / amazing / wonderful", "sr": "fantastičan / neverovatan / divan"},
            {"en": "in 1974 / in the 1970s", "sr": "1974. godine / u sedamdesetim"},
            {"en": "yesterday / last week / last year", "sr": "juče / prošle nedelje / prošle godine"},
            {"en": "two years ago", "sr": "pre dve godine"},
        ],
        "phrases": [
            {"en": "I was born in Liverpool in 1974.", "sr": "Rođen sam u Liverpulu 1974."},
            {"en": "It was a fantastic party!", "sr": "Bila je fantastična žurka!"},
            {"en": "There were thirty people.", "sr": "Bilo je trideset ljudi."},
            {"en": "My best friend wasn't here because he was ill.", "sr": "Najbolji drug nije bio tu jer je bio bolestan."},
            {"en": "There weren't any girls my age.", "sr": "Nije bilo devojaka mojih godina."},
            {"en": "Was the food good? — Yes, it was.", "sr": "Da li je hrana bila dobra? — Da."},
        ],
        "grammar": [
            {"en": "I/he/she/it was; you/we/they were", "sr": "Past Simple od BE"},
            {"en": "wasn't / weren't", "sr": "negacije: nije bio / nisu bili"},
            {"en": "Was she happy? Were they here?", "sr": "Pitanja: Was/Were + subj.?"},
        ],
    },
    "5b": {
        "vocab": [
            {"en": "leave school / university", "sr": "završiti školu / fakultet"},
            {"en": "meet (your husband/wife)", "sr": "upoznati (muža/ženu)"},
            {"en": "get married / divorced", "sr": "venčati se / razvesti se"},
            {"en": "make a film / make a lot of money", "sr": "snimiti film / zaraditi mnogo novca"},
            {"en": "become a film director / famous", "sr": "postati reditelj / poznat"},
            {"en": "have children / a dream", "sr": "imati decu / san"},
            {"en": "move (house / to a different country)", "sr": "preseliti se"},
            {"en": "study English / physics", "sr": "učiti engleski / fiziku"},
            {"en": "write a book / a letter", "sr": "napisati knjigu / pismo"},
            {"en": "win an Oscar / the lottery", "sr": "osvojiti Oskar / lutriju"},
            {"en": "be born", "sr": "roditi se"},
        ],
        "phrases": [
            {"en": "James Cameron was born in 1954.", "sr": "Džejms Kameron je rođen 1954."},
            {"en": "His family moved to the USA in 1971.", "sr": "Porodica se preselila u SAD 1971."},
            {"en": "He left university after only two years.", "sr": "Ostavio je fakultet posle samo dve godine."},
            {"en": "He worked as a bus driver.", "sr": "Radio je kao vozač autobusa."},
            {"en": "Titanic made $2 billion and won eleven Oscars.", "sr": "Titanik je zaradio 2 milijarde i osvojio 11 Oskara."},
            {"en": "James met Linda Hamilton in 1984.", "sr": "Džejms je upoznao Lindu Hamilton 1984."},
            {"en": "They got divorced in 1999.", "sr": "Razveli su se 1999."},
        ],
        "grammar": [
            {"en": "worked, studied, lived (regular -ed)", "sr": "Pravilni: dodavanje -ed"},
            {"en": "be → was/were; have → had; go → went; do → did", "sr": "Nepravilni glagoli (1)"},
            {"en": "get → got; make → made; meet → met; win → won; write → wrote", "sr": "Nepravilni glagoli (2)"},
            {"en": "When did James Cameron start? (Wh- pitanje)", "sr": "Wh- + did + subj. + bazni glagol"},
        ],
    },
    "5c": {
        "vocab": [
            {"en": "go for a walk / a run", "sr": "otići u šetnju / na trčanje"},
            {"en": "clean the house / the car", "sr": "čistiti kuću / auto"},
            {"en": "do the washing / your homework", "sr": "prati veš / raditi domaći"},
            {"en": "write an email / a report", "sr": "napisati imejl / izveštaj"},
            {"en": "go away for the weekend", "sr": "otputovati za vikend"},
            {"en": "go away for a couple of days", "sr": "otputovati na par dana"},
            {"en": "have a great time / a bad cold", "sr": "lepo se provesti / imati prehladu"},
            {"en": "go to your parents' house / for lunch", "sr": "otići kod roditelja / na ručak"},
            {"en": "stay at home all weekend", "sr": "ostati kod kuće ceo vikend"},
            {"en": "stay with friends", "sr": "biti kod prijatelja u poseti"},
        ],
        "phrases": [
            {"en": "How was your weekend?", "sr": "Kako ti je bio vikend?"},
            {"en": "What did you do last weekend?", "sr": "Šta si radio/la prošlog vikenda?"},
            {"en": "I went for a walk on Sunday.", "sr": "Otišao/-la sam u šetnju u nedelju."},
            {"en": "Me too. / Did you?", "sr": "I ja. / Stvarno?"},
            {"en": "Really? That's interesting.", "sr": "Stvarno? Zanimljivo."},
            {"en": "Sounds great!", "sr": "Zvuči odlično!"},
            {"en": "Who did you go with?", "sr": "S kim si išao/la?"},
            {"en": "I'm sorry I wasn't at the party.", "sr": "Žao mi je što nisam bio/la na žurci."},
        ],
    },
    "5d": {
        "vocab": [
            {"en": "bored", "sr": "kome je dosadno"},
            {"en": "crowded", "sr": "prepun, krcat"},
            {"en": "busy", "sr": "zauzet / živahan"},
            {"en": "comfortable", "sr": "udoban"},
            {"en": "clean ↔ dirty", "sr": "čist ↔ prljav"},
            {"en": "rich ↔ poor", "sr": "bogat ↔ siromašan"},
            {"en": "dangerous ↔ safe", "sr": "opasan ↔ bezbedan"},
            {"en": "excited", "sr": "uzbuđen"},
            {"en": "empty ↔ full", "sr": "prazan ↔ pun"},
        ],
        "phrases": [
            {"en": "I won a weekend for two in Krakow.", "sr": "Dobio sam vikend za dvoje u Krakovu."},
            {"en": "The hotel was really comfortable.", "sr": "Hotel je bio jako udoban."},
            {"en": "It was quite crowded.", "sr": "Bilo je dosta gužve."},
            {"en": "The food was fantastic!", "sr": "Hrana je bila fantastična!"},
            {"en": "The hotel was really awful.", "sr": "Hotel je bio užasan."},
            {"en": "We didn't leave the hotel because it was too cold.", "sr": "Nismo izašli iz hotela jer je bilo previše hladno."},
            {"en": "It was a terrible weekend!", "sr": "Bio je grozan vikend!"},
        ],
        "grammar": [
            {"en": "very + adj. (jako, neutralno): very good", "sr": "jako (pozitivno/neutralno)"},
            {"en": "really + adj. (stvarno, naglašeno): really interesting", "sr": "stvarno"},
            {"en": "quite + adj. (umereno, BrE): quite long", "sr": "prilično (blaže)"},
            {"en": "too + adj. (previše, negativno): too cold", "sr": "previše (uvek loše)"},
        ],
    },
    # =================================================================
    # UNIT 6
    # =================================================================
    "6a": {
        "vocab": [
            {"en": "use the internet", "sr": "koristiti internet"},
            {"en": "send / get an email", "sr": "poslati / dobiti imejl"},
            {"en": "read a blog", "sr": "čitati blog"},
            {"en": "chat (online)", "sr": "ćaskati (onlajn)"},
            {"en": "download videos / music", "sr": "preuzimati klipove / muziku"},
            {"en": "go online", "sr": "biti onlajn"},
            {"en": "have a favourite website", "sr": "imati omiljen sajt"},
            {"en": "have WiFi", "sr": "imati Wi-Fi"},
            {"en": "use a search engine", "sr": "koristiti pretraživač"},
            {"en": "launch (a search engine)", "sr": "pokrenuti (pretraživač)"},
            {"en": "build (built)", "sr": "izgraditi (built)"},
            {"en": "a billionaire", "sr": "milijarder"},
            {"en": "a bank account", "sr": "bankovni račun"},
            {"en": "a cheque", "sr": "ček"},
        ],
        "phrases": [
            {"en": "Search engines weren't very good.", "sr": "Pretraživači nisu bili baš dobri."},
            {"en": "They didn't like each other at first.", "sr": "Nisu se sviđali jedan drugom u početku."},
            {"en": "Did you find it? — Yes, I did. / No, I didn't.", "sr": "Da li si ga našao? — Da. / Ne."},
            {"en": "What did they do in 1998?", "sr": "Šta su uradili 1998?"},
        ],
        "grammar": [
            {"en": "didn't + bazni glagol: I didn't go.", "sr": "Negacija u Past Simple"},
            {"en": "Did + subj. + bazni glagol …?", "sr": "Yes/No pitanje"},
            {"en": "Yes, I did. / No, I didn't.", "sr": "Kratki odgovori"},
        ],
    },
    "6b": {
        "vocab": [
            {"en": "send / get a text", "sr": "poslati / dobiti SMS"},
            {"en": "charge your phone", "sr": "puniti telefon"},
            {"en": "GPS", "sr": "GPS"},
            {"en": "a channel", "sr": "kanal (TV)"},
            {"en": "a TV programme", "sr": "TV emisija"},
            {"en": "a battery", "sr": "baterija"},
            {"en": "an app", "sr": "aplikacija"},
            {"en": "turn on / turn off", "sr": "uključiti / isključiti"},
            {"en": "record", "sr": "snimiti"},
            {"en": "five minutes ago", "sr": "pre pet minuta"},
            {"en": "yesterday / the day before yesterday", "sr": "juče / prekjuče"},
            {"en": "last Monday / last week", "sr": "prošlog ponedeljka / prošle nedelje"},
            {"en": "in May 2002 / in the nineties", "sr": "u maju 2002. / devedesetih"},
            {"en": "five years ago", "sr": "pre pet godina"},
        ],
        "phrases": [
            {"en": "I left school four years ago.", "sr": "Završio sam školu pre 4 godine."},
            {"en": "I went to bed late last Saturday.", "sr": "Legao sam kasno prošle subote."},
            {"en": "My parents got married in 1985.", "sr": "Moji su se venčali 1985."},
            {"en": "You couldn't record TV programmes.", "sr": "Nisi mogao da snimaš emisije."},
            {"en": "TV was in black and white.", "sr": "TV je bio crno-beli."},
        ],
        "grammar": [
            {"en": "I can swim. / He can't drive.", "sr": "Sadašnja sposobnost"},
            {"en": "I could read at five. / He couldn't speak French.", "sr": "Prošla sposobnost"},
            {"en": "Can you …? / Could you …? (no do/did)", "sr": "Pitanja bez do/did"},
        ],
    },
    "6c": {
        "vocab": [
            {"en": "damage", "sr": "oštetiti"},
            {"en": "die", "sr": "umreti"},
            {"en": "crash", "sr": "udariti, srušiti se"},
            {"en": "sail", "sr": "ploviti"},
            {"en": "receive", "sr": "primiti"},
            {"en": "save", "sr": "spasiti, sačuvati"},
            {"en": "buy → bought", "sr": "kupiti → kupio"},
            {"en": "find → found", "sr": "naći → našao"},
            {"en": "lose → lost", "sr": "izgubiti → izgubio"},
            {"en": "put → put", "sr": "staviti → stavio"},
            {"en": "tell → told", "sr": "reći → rekao"},
            {"en": "pay → paid", "sr": "platiti → platio"},
            {"en": "a train / a hospital / a storm", "sr": "voz / bolnica / oluja"},
            {"en": "a couple / missing / at sea", "sr": "par / nestao / na moru"},
            {"en": "the coast / a helicopter / a boat", "sr": "obala / helikopter / čamac"},
            {"en": "an envelope", "sr": "koverat"},
        ],
        "phrases": [
            {"en": "Here's George Lucan with the news.", "sr": "Evo Džordža Lukana sa vestima."},
            {"en": "Over 60 people are in hospital after a train crash.", "sr": "Preko 60 ljudi je u bolnici nakon udesa voza."},
            {"en": "There were storms in California last night.", "sr": "Sinoć su bili oluje u Kaliforniji."},
            {"en": "Joe Hall won over £3 million.", "sr": "Džou Hol je dobio preko 3 miliona funti."},
            {"en": "Did you hear about …?", "sr": "Jesi li čuo za …?"},
            {"en": "What happened?", "sr": "Šta se desilo?"},
            {"en": "That's terrible! / How awful!", "sr": "To je užasno! / Strašno!"},
        ],
    },
    "6d": {
        "vocab": [
            {"en": "a designer", "sr": "dizajner"},
            {"en": "art", "sr": "umetnost"},
            {"en": "an award", "sr": "nagrada"},
            {"en": "a hero", "sr": "junak"},
            {"en": "a villain", "sr": "negativac"},
            {"en": "a princess / a prince", "sr": "princeza / princ"},
            {"en": "a / an (general / first mention)", "sr": "a/an (uopšteno / prvi pomen)"},
            {"en": "the (specific / second mention)", "sr": "the (određeno / pominjano)"},
            {"en": "the sun / the moon / the internet", "sr": "jedinstveni: sunce / mesec / internet"},
        ],
        "phrases": [
            {"en": "Shigeru is a video game designer.", "sr": "Šigeru je dizajner igara."},
            {"en": "He works for Nintendo.", "sr": "Radi za Nintendo."},
            {"en": "He's married with two children.", "sr": "Oženjen je i ima dvoje dece."},
            {"en": "He met his wife at Nintendo.", "sr": "Upoznao je ženu u Nintendu."},
            {"en": "He goes to work by bike.", "sr": "Ide na posao biciklom."},
        ],
        "grammar": [
            {"en": "Mario is a video game character. The character is famous.", "sr": "a → prvo pominjanje, the → drugo"},
            {"en": "have lunch / go to school (no article)", "sr": "ustaljeni izrazi: bez člana"},
            {"en": "the news / the radio / the cinema", "sr": "the za jedinstveno"},
        ],
    },
    # =================================================================
    # UNIT 7
    # =================================================================
    "7a": {
        "vocab": [
            {"en": "a building", "sr": "zgrada"},
            {"en": "a house / a flat", "sr": "kuća / stan"},
            {"en": "a square", "sr": "trg"},
            {"en": "a market", "sr": "pijaca"},
            {"en": "a station / a bus station", "sr": "(železnička) stanica / autobuska stanica"},
            {"en": "a park", "sr": "park"},
            {"en": "a museum", "sr": "muzej"},
            {"en": "a theatre", "sr": "pozorište"},
            {"en": "a cinema", "sr": "bioskop"},
            {"en": "a hotel", "sr": "hotel"},
            {"en": "a café", "sr": "kafić"},
            {"en": "a shop", "sr": "prodavnica"},
            {"en": "a restaurant", "sr": "restoran"},
            {"en": "a bar / a pub", "sr": "bar / pab"},
            {"en": "an airport", "sr": "aerodrom"},
            {"en": "a road", "sr": "ulica/put"},
            {"en": "a beach", "sr": "plaža"},
            {"en": "a city / a small town / a village", "sr": "grad / grad(ić) / selo"},
        ],
        "phrases": [
            {"en": "We lived there for 12 years.", "sr": "Tamo smo živeli 12 godina."},
            {"en": "I stayed at home all weekend.", "sr": "Ostao sam kod kuće ceo vikend."},
            {"en": "It's about two hours from the airport.", "sr": "Oko dva sata od aerodroma."},
            {"en": "All of the houses are different colours.", "sr": "Sve kuće su raznih boja."},
            {"en": "There's a beautiful park.", "sr": "Postoji prelep park."},
            {"en": "There are some nice cafés.", "sr": "Ima nekoliko lepih kafića."},
        ],
        "grammar": [
            {"en": "There is + jednina: There's a park.", "sr": "Postoji (jednina)"},
            {"en": "There are + množina: There are shops.", "sr": "Postoje (množina)"},
            {"en": "There isn't / There aren't (any)", "sr": "Negacija"},
            {"en": "Is there …? / Are there any …?", "sr": "Pitanje"},
            {"en": "How many shops are there?", "sr": "Koliko ima prodavnica?"},
        ],
    },
    "7b": {
        "vocab": [
            {"en": "furniture", "sr": "nameštaj"},
            {"en": "a double bed / a single bed", "sr": "bračni / jednostruki krevet"},
            {"en": "a fridge", "sr": "frižider"},
            {"en": "a coffee table", "sr": "klub-stočić"},
            {"en": "a bath / a shower", "sr": "kada / tuš"},
            {"en": "a cooker", "sr": "šporet"},
            {"en": "a toilet", "sr": "WC"},
            {"en": "a sink", "sr": "sudopera"},
            {"en": "a desk", "sr": "radni sto"},
            {"en": "a sofa / an armchair", "sr": "kauč / fotelja"},
            {"en": "a washing machine", "sr": "veš mašina"},
            {"en": "a washbasin", "sr": "umivaonik"},
            {"en": "a table / a chair / a cupboard / a shelf", "sr": "sto / stolica / orman / polica"},
            {"en": "a kitchen / a living room / a bathroom / a bedroom", "sr": "kuhinja / dnevni boravak / kupatilo / spavaća soba"},
            {"en": "a balcony / a garden", "sr": "balkon / bašta"},
        ],
        "phrases": [
            {"en": "How much space is there?", "sr": "Koliko prostora ima?"},
            {"en": "How many bedrooms are there?", "sr": "Koliko spavaćih soba ima?"},
            {"en": "How much is the rent?", "sr": "Kolika je kirija?"},
            {"en": "There aren't any plants.", "sr": "Nema nijedne biljke."},
            {"en": "There's some furniture in the living room.", "sr": "Ima nešto nameštaja u dnevnoj sobi."},
        ],
        "grammar": [
            {"en": "How much milk? (uncountable)", "sr": "Koliko mleka? (nebrojivo)"},
            {"en": "How many chairs? (countable)", "sr": "Koliko stolica? (brojivo)"},
            {"en": "some (potvrda/ponuda) / any (pitanje/negacija)", "sr": "razlika some/any"},
            {"en": "a + jednina: a chair", "sr": "neodređeni član"},
        ],
    },
    "7c": {
        "vocab": [
            {"en": "a bookshop", "sr": "knjižara"},
            {"en": "a clothes shop", "sr": "prodavnica odeće"},
            {"en": "a shoe shop", "sr": "prodavnica obuće"},
            {"en": "a supermarket", "sr": "supermarket"},
            {"en": "a kiosk", "sr": "kiosk"},
            {"en": "a newsagent's", "sr": "trafika (sa novinama)"},
            {"en": "a post office", "sr": "pošta"},
            {"en": "a butcher's", "sr": "mesara"},
            {"en": "a department store", "sr": "robna kuća"},
            {"en": "a bank", "sr": "banka"},
            {"en": "a chemist's", "sr": "apoteka"},
            {"en": "a baker's", "sr": "pekara"},
            {"en": "a suitcase / a lamp / a guide book", "sr": "kofer / lampa / vodič"},
            {"en": "stamps", "sr": "marke (poštanske)"},
            {"en": "tissues", "sr": "papirne maramice"},
            {"en": "postcards / a newspaper / a map", "sr": "razglednice / novine / mapa"},
            {"en": "aspirin", "sr": "aspirin"},
            {"en": "a cake / chocolate", "sr": "kolač / čokolada"},
            {"en": "cigarettes", "sr": "cigarete"},
        ],
        "phrases": [
            {"en": "Can I help you?", "sr": "Mogu li da vam pomognem?"},
            {"en": "Do you need any help?", "sr": "Treba li vam pomoć?"},
            {"en": "Anything else? / Would you like anything else?", "sr": "Još nešto? / Želite li još nešto?"},
            {"en": "Would you like a bag?", "sr": "Želite li kesu?"},
            {"en": "That's £17.50, please.", "sr": "Iznos je 17,50 funti."},
            {"en": "Your PIN number, please.", "sr": "Vaš PIN, molim."},
            {"en": "Here's your change and your receipt.", "sr": "Izvolite kusur i račun."},
            {"en": "They're on the second floor.", "sr": "Na drugom su spratu."},
            {"en": "I'm just looking, thanks.", "sr": "Samo gledam, hvala."},
            {"en": "I'd like a map of London, please.", "sr": "Želeo/-la bih kartu Londona, molim."},
            {"en": "How much is it?", "sr": "Koliko košta?"},
            {"en": "Can I pay by card / in cash?", "sr": "Mogu li platiti karticom / kešom?"},
        ],
    },
    "7d": {
        "vocab": [
            {"en": "trousers", "sr": "pantalone"},
            {"en": "shorts", "sr": "šorts"},
            {"en": "jeans", "sr": "farmerke"},
            {"en": "a dress", "sr": "haljina"},
            {"en": "shoes", "sr": "cipele"},
            {"en": "a suit", "sr": "odelo"},
            {"en": "a skirt", "sr": "suknja"},
            {"en": "a jumper", "sr": "džemper"},
            {"en": "trainers", "sr": "patike"},
            {"en": "a jacket", "sr": "jakna"},
            {"en": "a hat", "sr": "šešir/kapa"},
            {"en": "a tie", "sr": "kravata"},
            {"en": "boots", "sr": "čizme"},
            {"en": "socks", "sr": "čarape"},
            {"en": "a T-shirt / a top", "sr": "majica / top"},
            {"en": "a coat", "sr": "kaput"},
            {"en": "a cap", "sr": "kačket"},
            {"en": "a shirt", "sr": "košulja"},
            {"en": "black / white / red / blue / yellow / grey", "sr": "crna / bela / crvena / plava / žuta / siva"},
            {"en": "pink / brown / orange / purple", "sr": "roze / smeđa / narandžasta / ljubičasta"},
            {"en": "dark green / light green", "sr": "tamnozelena / svetlozelena"},
        ],
        "phrases": [
            {"en": "I usually wear a suit in the week.", "sr": "Obično nosim odelo radnim danima."},
            {"en": "I never wear pink.", "sr": "Nikad ne nosim roze."},
            {"en": "I've got a pair of red jeans.", "sr": "Imam jedne crvene farmerke."},
            {"en": "Where are my shoes?", "sr": "Gde su mi cipele?"},
            {"en": "Those jeans are nice.", "sr": "Te farmerke su lepe."},
            {"en": "I want to buy a dress for a party.", "sr": "Želim da kupim haljinu za žurku."},
        ],
        "grammar": [
            {"en": "I haven't got any white shirts.", "sr": "any u negaciji"},
            {"en": "I've got some black jeans.", "sr": "some u potvrdi"},
            {"en": "I need a new pair of trainers.", "sr": "a + pair of"},
            {"en": "jeans, trousers, shorts (always plural)", "sr": "uvek u množini (kažemo a pair of …)"},
        ],
    },
    # =================================================================
    # UNIT 8
    # =================================================================
    "8a": {
        "vocab": [
            {"en": "a customer", "sr": "kupac/klijent"},
            {"en": "a report", "sr": "izveštaj"},
            {"en": "notes", "sr": "beleške"},
            {"en": "a letter", "sr": "pismo"},
            {"en": "a message", "sr": "poruka"},
            {"en": "a contract", "sr": "ugovor"},
            {"en": "a company", "sr": "firma"},
            {"en": "a meeting", "sr": "sastanak"},
            {"en": "a conference", "sr": "konferencija"},
            {"en": "write a report / a letter", "sr": "pisati izveštaj / pismo"},
            {"en": "answer the phone / an email", "sr": "odgovoriti na telefon / mejl"},
            {"en": "take messages / notes", "sr": "primiti poruku / beležiti"},
            {"en": "sign a contract / a letter", "sr": "potpisati ugovor / pismo"},
            {"en": "work for a company / in an office", "sr": "raditi za firmu / u kancelariji"},
            {"en": "go to a meeting / a conference", "sr": "ići na sastanak / konferenciju"},
            {"en": "write to a customer / a company", "sr": "pisati klijentu / firmi"},
        ],
        "phrases": [
            {"en": "I'm waiting for a taxi.", "sr": "Čekam taksi."},
            {"en": "They're sitting in your office.", "sr": "Sede u tvojoj kancelariji."},
            {"en": "She's working at home today.", "sr": "Danas radi od kuće."},
            {"en": "I'm not doing anything important at the moment.", "sr": "Trenutno ne radim ništa važno."},
            {"en": "They aren't looking very happy.", "sr": "Ne deluju srećno."},
        ],
        "grammar": [
            {"en": "I'm + verb-ing / He's + verb-ing", "sr": "Present Continuous (sada)"},
            {"en": "play → playing; make → making (briše se -e)", "sr": "Pravopis: -e otpada"},
            {"en": "sit → sitting; run → running (dupliranje)", "sr": "CVC → dupliranje suglasnika"},
            {"en": "lie → lying", "sr": "ie → ying"},
            {"en": "Are you working? — Yes, I am. / No, I'm not.", "sr": "Pitanje i kratak odgovor"},
        ],
    },
    "8b": {
        "vocab": [
            {"en": "a car", "sr": "auto"},
            {"en": "a plane", "sr": "avion"},
            {"en": "a train", "sr": "voz"},
            {"en": "a taxi", "sr": "taksi"},
            {"en": "a bus / a coach", "sr": "autobus / autobus za daljinu"},
            {"en": "a tram", "sr": "tramvaj"},
            {"en": "a bike", "sr": "bicikl"},
            {"en": "a scooter", "sr": "skuter"},
            {"en": "a boat / a ferry", "sr": "čamac / trajekt"},
            {"en": "a motorbike", "sr": "motor"},
            {"en": "go by car / by bike / by plane", "sr": "ići autom / biciklom / avionom"},
            {"en": "go on foot", "sr": "ići peške"},
            {"en": "drive / cycle / fly / walk", "sr": "voziti (auto) / voziti (bicikl) / leteti / hodati"},
            {"en": "take the bus / the tube / the train", "sr": "ići autobusom / metroom / vozom"},
            {"en": "snow / a traffic jam / a journey", "sr": "sneg / saobraćajna gužva / putovanje"},
        ],
        "phrases": [
            {"en": "Heavy snow continues to fall in central London.", "sr": "Jak sneg pada u centru Londona."},
            {"en": "How do you usually get to work?", "sr": "Kako obično ideš na posao?"},
            {"en": "I usually drive, but today I'm taking the bus.", "sr": "Obično vozim, ali danas idem autobusom."},
            {"en": "She's travelling by train today.", "sr": "Danas putuje vozom."},
        ],
        "grammar": [
            {"en": "Present Simple (every day) vs. Present Continuous (now/today)", "sr": "Razlika dva vremena"},
            {"en": "I usually walk, but today I'm cycling.", "sr": "Tipičan kontrast"},
            {"en": "Stative verbs: know, like, want, need (no -ing)", "sr": "Glagoli stanja ne idu u Continuous"},
        ],
    },
    "8c": {
        "vocab": [
            {"en": "voicemail", "sr": "govorna pošta"},
            {"en": "leave a message", "sr": "ostaviti poruku"},
            {"en": "press a number", "sr": "pritisnuti broj"},
            {"en": "the tone", "sr": "tonski signal"},
            {"en": "an enquiry", "sr": "upit"},
            {"en": "a phone call", "sr": "telefonski poziv"},
            {"en": "a conference", "sr": "konferencija"},
            {"en": "a theatre", "sr": "pozorište"},
            {"en": "an actor", "sr": "glumac"},
        ],
        "phrases": [
            {"en": "Hello, this is Alan Wick's voicemail.", "sr": "Halo, ovo je govorna pošta Alana Vika."},
            {"en": "If you leave a message, I'll get back to you.", "sr": "Ako ostavite poruku, javiću vam se."},
            {"en": "I'm sorry, but the person you called is not available.", "sr": "Žao mi je, osoba koju zovete nije dostupna."},
            {"en": "Please leave your message after the tone.", "sr": "Ostavite poruku posle signala."},
            {"en": "Please choose one of the following three options.", "sr": "Izaberite jednu od tri opcije."},
            {"en": "For all other enquiries, press zero.", "sr": "Za ostala pitanja pritisnite nulu."},
            {"en": "Please try again later.", "sr": "Pokušajte ponovo kasnije."},
            {"en": "Hello, can I speak to …, please?", "sr": "Halo, mogu li da pričam sa …?"},
            {"en": "Hold on, please.", "sr": "Sačekajte, molim."},
            {"en": "Can I take a message?", "sr": "Da li da prenesem poruku?"},
            {"en": "I'll call back later.", "sr": "Pozvaću kasnije."},
        ],
    },
    "8d": {
        "vocab": [
            {"en": "swim", "sr": "plivati"},
            {"en": "ski", "sr": "skijati se"},
            {"en": "surf", "sr": "surfovati"},
            {"en": "windsurf", "sr": "vindsurfovati"},
            {"en": "sail", "sr": "ploviti, jedriti"},
            {"en": "sing", "sr": "pevati"},
            {"en": "cook", "sr": "kuvati"},
            {"en": "drive", "sr": "voziti"},
            {"en": "speak another language", "sr": "govoriti drugi jezik"},
            {"en": "ride a horse", "sr": "jahati"},
            {"en": "ride a motorbike", "sr": "voziti motor"},
            {"en": "play a musical instrument", "sr": "svirati instrument"},
            {"en": "fluent → fluently", "sr": "tečan → tečno"},
            {"en": "easy → easily", "sr": "lak → lako"},
            {"en": "careful → carefully", "sr": "pažljiv → pažljivo"},
            {"en": "good → well (irregular)", "sr": "dobar → dobro (nepravilno)"},
            {"en": "hard → hard (same form)", "sr": "marljiv → marljivo (isti oblik)"},
            {"en": "fast → fast", "sr": "brz → brzo"},
        ],
        "phrases": [
            {"en": "Can you swim? — Yes, I can. / No, I can't.", "sr": "Znaš li da plivaš? — Da. / Ne."},
            {"en": "He speaks Spanish fluently.", "sr": "On tečno govori španski."},
            {"en": "He is an excellent driver.", "sr": "On je odličan vozač."},
            {"en": "He always worked hard.", "sr": "Uvek je marljivo radio."},
            {"en": "I am writing to recommend Ray.", "sr": "Pišem da preporučim Reja."},
            {"en": "Yours faithfully", "sr": "S poštovanjem (kraj formalnog pisma)"},
        ],
        "grammar": [
            {"en": "Pridev opisuje imenicu: a careful driver", "sr": "Pridev → imenica"},
            {"en": "Prilog opisuje glagol: drives carefully", "sr": "Prilog → glagol"},
            {"en": "He works hard (= mnogo) ↔ He hardly works (= jedva)", "sr": "Pažnja: hard vs. hardly"},
        ],
    },
    # =================================================================
    # UNIT 9
    # =================================================================
    "9a": {
        "vocab": [
            {"en": "have a picnic", "sr": "ići na piknik"},
            {"en": "have a good time", "sr": "lepo se provesti"},
            {"en": "stay in a hotel", "sr": "odsesti u hotelu"},
            {"en": "stay with friends or family", "sr": "biti kod prijatelja/porodice"},
            {"en": "rent a car / a bike / a boat", "sr": "iznajmiti auto / bicikl / čamac"},
            {"en": "go sightseeing", "sr": "razgledati znamenitosti"},
            {"en": "go diving", "sr": "ići na ronjenje"},
            {"en": "go skiing", "sr": "ići na skijanje"},
            {"en": "go camping", "sr": "kampovati"},
            {"en": "go to museums", "sr": "ići u muzeje"},
            {"en": "go to the beach", "sr": "ići na plažu"},
            {"en": "go on holiday", "sr": "ići na odmor"},
            {"en": "go on a boat trip", "sr": "ići na vožnju brodom"},
            {"en": "go on a guided tour", "sr": "ići na vođenu turu"},
            {"en": "travel by public transport", "sr": "putovati javnim prevozom"},
            {"en": "travel around (the country)", "sr": "obilaziti zemlju"},
        ],
        "phrases": [
            {"en": "When did you last go on holiday?", "sr": "Kad si poslednji put bio/-la na odmoru?"},
            {"en": "Where did you go?", "sr": "Gde si išao/-la?"},
            {"en": "Did you have a good time?", "sr": "Da li si se lepo proveo/-la?"},
            {"en": "Who did you go with?", "sr": "S kim si išao/-la?"},
            {"en": "What did you do there?", "sr": "Šta si radio/-la tamo?"},
            {"en": "How did you travel around?", "sr": "Kako si se kretao/-la po mestu?"},
            {"en": "We went to Cape Town to relax.", "sr": "Otišli smo u Kejptaun da se odmorimo."},
            {"en": "I'm calling to ask a question.", "sr": "Zovem da pitam nešto."},
        ],
        "grammar": [
            {"en": "to + verb (purpose): I went there to study.", "sr": "Infinitiv namene: zbog čega"},
            {"en": "for + noun: He went there for a holiday.", "sr": "for + imenica: zbog čega"},
        ],
    },
    "9b": {
        "vocab": [
            {"en": "the countryside", "sr": "priroda, predeo van grada"},
            {"en": "a mountain", "sr": "planina"},
            {"en": "a hill", "sr": "brdo"},
            {"en": "a forest", "sr": "šuma (velika)"},
            {"en": "a wood", "sr": "šuma (manja)"},
            {"en": "a river", "sr": "reka"},
            {"en": "an island", "sr": "ostrvo"},
            {"en": "a lake", "sr": "jezero"},
            {"en": "the sea", "sr": "more"},
            {"en": "the desert", "sr": "pustinja"},
            {"en": "the Pyramids", "sr": "Piramide"},
            {"en": "a mosque", "sr": "džamija"},
            {"en": "go snorkelling", "sr": "ići na ronjenje s maskom"},
            {"en": "a coral reef", "sr": "koralni greben"},
            {"en": "a camel", "sr": "kamila"},
        ],
        "phrases": [
            {"en": "The Sels Hotel is smaller than the Shokran Hotel.", "sr": "Sels je manji od Šokrana."},
            {"en": "Cairo is hotter than Sharm El Sheikh.", "sr": "Kairo je topliji od Šarm el Šejha."},
            {"en": "Cairo is more crowded.", "sr": "Kairo je gušće naseljen."},
            {"en": "The holiday in Cairo is more expensive.", "sr": "Odmor u Kairu je skuplji."},
        ],
        "grammar": [
            {"en": "small → smaller; old → older", "sr": "1 slog: -er"},
            {"en": "big → bigger; hot → hotter (CVC dupliranje)", "sr": "Dupliranje suglasnika"},
            {"en": "noisy → noisier; happy → happier", "sr": "y → ier"},
            {"en": "expensive → more expensive; crowded → more crowded", "sr": "Duži pridevi: more"},
            {"en": "good → better; bad → worse", "sr": "Nepravilni"},
            {"en": "X is smaller than Y.", "sr": "than = nego"},
        ],
    },
    "9c": {
        "vocab": [
            {"en": "a lion / a tiger", "sr": "lav / tigar"},
            {"en": "a chicken", "sr": "kokoš"},
            {"en": "a cow", "sr": "krava"},
            {"en": "a monkey / a gorilla", "sr": "majmun / gorila"},
            {"en": "a sheep", "sr": "ovca"},
            {"en": "a wolf", "sr": "vuk"},
            {"en": "a rabbit", "sr": "zec"},
            {"en": "a mouse", "sr": "miš"},
            {"en": "a snake", "sr": "zmija"},
            {"en": "a bird", "sr": "ptica"},
            {"en": "wild animals", "sr": "divlje životinje"},
            {"en": "farm animals", "sr": "domaće životinje"},
            {"en": "pets", "sr": "kućni ljubimci"},
        ],
        "phrases": [
            {"en": "What would you like to do?", "sr": "Šta biste voleli da radite?"},
            {"en": "Why don't we go to the zoo?", "sr": "Zašto da ne idemo u zoo?"},
            {"en": "How about a boat trip?", "sr": "Šta misliš o vožnji čamcem?"},
            {"en": "Let's have lunch in the park.", "sr": "Hajde da ručamo u parku."},
            {"en": "That's a great idea.", "sr": "To je odlična ideja."},
            {"en": "I'm not sure.", "sr": "Nisam baš siguran/-na."},
            {"en": "OK, let's do that.", "sr": "Ok, hajde da to uradimo."},
        ],
    },
    "9d": {
        "vocab": [
            {"en": "love + verb-ing", "sr": "obožavati nešto da radim (uopšteno)"},
            {"en": "like + verb-ing", "sr": "voleti (uopšteno)"},
            {"en": "enjoy + verb-ing", "sr": "uživati u (uopšteno)"},
            {"en": "hate + verb-ing", "sr": "mrzeti (uopšteno)"},
            {"en": "would like + to + verb", "sr": "rado bih, voleo bih (sada/jednom)"},
            {"en": "want + to + verb", "sr": "hteti da uradim"},
            {"en": "need + to + verb", "sr": "trebati da uradim"},
            {"en": "I'd = I would", "sr": "skraćeni oblik"},
        ],
        "phrases": [
            {"en": "I really enjoy spending time with my family.", "sr": "Stvarno uživam u vremenu sa porodicom."},
            {"en": "I'd love to live in the country one day.", "sr": "Voleo bih da jednog dana živim na selu."},
            {"en": "Teenagers like going out on their own.", "sr": "Tinejdžeri vole da izlaze sami."},
            {"en": "Would you like to move house?", "sr": "Da li bi se preselio/-la?"},
            {"en": "Yes, I'd love to. / No, I wouldn't.", "sr": "Da, rado bih. / Ne, ne bih."},
            {"en": "I stopped looking for work in the country.", "sr": "Prestao sam da tražim posao na selu."},
            {"en": "I need to find a job.", "sr": "Treba da nađem posao."},
        ],
    },
    # =================================================================
    # UNIT 10
    # =================================================================
    "10a": {
        "vocab": [
            {"en": "wash the windows / the car", "sr": "oprati prozore / auto"},
            {"en": "get fit / stressed", "sr": "biti u formi / nervozan"},
            {"en": "save time / money", "sr": "uštedeti vreme / novac"},
            {"en": "carry the shopping / the bags", "sr": "nositi kupovinu / torbe"},
            {"en": "take a bath / a shower", "sr": "okupati se / istuširati se"},
            {"en": "have a bus / a train", "sr": "(uhvatiti) autobus / voz"},
            {"en": "do the housework / some exercise", "sr": "obaviti kućne poslove / vežbati"},
            {"en": "get on / off the bus", "sr": "ući u / izaći iz autobusa"},
            {"en": "go for a run", "sr": "ići na trčanje"},
            {"en": "once a week", "sr": "jednom nedeljno"},
            {"en": "twice a week", "sr": "dva puta nedeljno"},
            {"en": "three times a week", "sr": "tri puta nedeljno"},
            {"en": "a member / a survey / a calorie / a mile", "sr": "član / anketa / kalorija / milja"},
            {"en": "healthy", "sr": "zdrav"},
        ],
        "phrases": [
            {"en": "Walk up and down stairs. Don't take lifts.", "sr": "Hodaj uz/niz stepenice. Ne koristi liftove."},
            {"en": "Get off the bus one stop earlier.", "sr": "Izađi jednu stanicu ranije."},
            {"en": "Don't drive to the supermarket.", "sr": "Ne idi autom u supermarket."},
            {"en": "Have a shower instead of a bath.", "sr": "Tuširaj se umesto kupanja."},
            {"en": "Go for a run twice a week.", "sr": "Trči dva puta nedeljno."},
            {"en": "You should walk more.", "sr": "Trebalo bi više da hodaš."},
            {"en": "You shouldn't sit all day.", "sr": "Ne bi trebalo ceo dan da sediš."},
        ],
        "grammar": [
            {"en": "Eat fruit. / Don't smoke.", "sr": "Imperativ: bazni glagol bez subjekta"},
            {"en": "should / shouldn't + bazni glagol", "sr": "Savet (blag oblik)"},
        ],
    },
    "10b": {
        "vocab": [
            {"en": "young / middle-aged / old", "sr": "mlad / srednjih godina / star"},
            {"en": "tall / short", "sr": "visok / nizak"},
            {"en": "thin / slim / fat / overweight", "sr": "mršav / vitak / debeo / gojazan"},
            {"en": "beautiful / good-looking / attractive", "sr": "lep / zgodan / privlačan"},
            {"en": "white / black / Asian", "sr": "belac / crnac / Azijat"},
            {"en": "blue/brown/green eyes", "sr": "plave / smeđe / zelene oči"},
            {"en": "long / short hair", "sr": "duga / kratka kosa"},
            {"en": "dark / fair / blonde / grey hair", "sr": "tamna / svetla / plava / sedа kosa"},
            {"en": "a beard", "sr": "brada"},
            {"en": "a moustache", "sr": "brkovi"},
            {"en": "kind", "sr": "ljubazan"},
            {"en": "shy", "sr": "stidljiv"},
            {"en": "generous", "sr": "darežljiv"},
            {"en": "lazy / hard-working", "sr": "lenj / vredan"},
            {"en": "friendly", "sr": "prijateljski raspoložen"},
            {"en": "selfish", "sr": "sebičan"},
            {"en": "funny", "sr": "smešan"},
            {"en": "reliable", "sr": "pouzdan"},
        ],
        "phrases": [
            {"en": "What's he like?", "sr": "Kakav je on (po karakteru)?"},
            {"en": "What does he look like?", "sr": "Kako on izgleda?"},
            {"en": "What does he like?", "sr": "Šta voli?"},
            {"en": "He's tall with short dark hair.", "sr": "Visok je, kratke tamne kose."},
            {"en": "She's kind and very friendly.", "sr": "Ljubazna je i vrlo prijateljski raspoložena."},
            {"en": "He's got a beard.", "sr": "Ima bradu."},
        ],
        "grammar": [
            {"en": "have got + appearance: She's got blue eyes, long hair.", "sr": "have got za izgled"},
            {"en": "be + appearance/character: She is tall / kind.", "sr": "be za visinu/karakter"},
        ],
    },
    "10c": {
        "vocab": [
            {"en": "a cold", "sr": "prehlada"},
            {"en": "a cough", "sr": "kašalj"},
            {"en": "a headache", "sr": "glavobolja"},
            {"en": "a sore throat", "sr": "upala grla"},
            {"en": "a stomach ache", "sr": "bol u stomaku"},
            {"en": "(I've got the) flu", "sr": "imam grip"},
            {"en": "toothache", "sr": "zubobolja"},
            {"en": "a temperature", "sr": "temperatura"},
            {"en": "I feel sick.", "sr": "Muka mi je."},
            {"en": "My back hurts.", "sr": "Boli me leđa."},
            {"en": "My arm / leg / foot hurts.", "sr": "Boli me ruka / noga / stopalo."},
            {"en": "go to the doctor / the dentist", "sr": "ići kod lekara / zubara"},
            {"en": "stay in bed / at home", "sr": "ostati u krevetu / kod kuće"},
            {"en": "take the day off", "sr": "uzeti slobodan dan"},
            {"en": "take painkillers", "sr": "popiti lekove protiv bolova"},
            {"en": "take cough medicine", "sr": "uzeti sirup za kašalj"},
            {"en": "take antibiotics", "sr": "uzeti antibiotike"},
        ],
        "phrases": [
            {"en": "What's the matter?", "sr": "Šta nije u redu?"},
            {"en": "I've got a headache.", "sr": "Boli me glava."},
            {"en": "You should rest.", "sr": "Trebalo bi da se odmoriš."},
            {"en": "You shouldn't go to work.", "sr": "Nemoj da ideš na posao."},
            {"en": "When I've got a cold, I usually stay in bed.", "sr": "Kad sam prehlađen/-na, obično ležim."},
            {"en": "Get well soon!", "sr": "Brzo ozdravi!"},
            {"en": "Oh dear. / That's terrible!", "sr": "Joj, baš mi je žao. / Užas!"},
            {"en": "I hope you get better soon.", "sr": "Nadam se da ćeš se brzo oporaviti."},
        ],
    },
    "10d": {
        "vocab": [
            {"en": "spring / summer / autumn / winter", "sr": "proleće / leto / jesen / zima"},
            {"en": "sunny", "sr": "sunčano"},
            {"en": "cloudy", "sr": "oblačno"},
            {"en": "windy", "sr": "vetrovito"},
            {"en": "rainy / It's raining.", "sr": "kišovito / pada kiša"},
            {"en": "snowy / It's snowing.", "sr": "snežno / pada sneg"},
            {"en": "foggy", "sr": "magla"},
            {"en": "hot / warm / cool / cold", "sr": "vruće / toplo / sveže / hladno"},
            {"en": "depressed", "sr": "depresivan"},
            {"en": "a scientist", "sr": "naučnik"},
            {"en": "bright light", "sr": "jaka svetlost"},
        ],
        "phrases": [
            {"en": "What's the weather like?", "sr": "Kakvo je vreme?"},
            {"en": "It's hot. / It's raining.", "sr": "Vruće je. / Pada kiša."},
            {"en": "A lot of people feel depressed in winter.", "sr": "Mnogi se osećaju depresivno zimi."},
            {"en": "People with SAD usually sleep a lot.", "sr": "Ljudi sa SAD obično mnogo spavaju."},
            {"en": "The best treatment is bright light.", "sr": "Najbolji lek je jaka svetlost."},
        ],
        "grammar": [
            {"en": "sun → sunny; cloud → cloudy; wind → windy", "sr": "imenica + -y → pridev"},
            {"en": "fog → foggy; rain → rainy", "sr": "isto pravilo"},
        ],
    },
    # =================================================================
    # UNIT 11
    # =================================================================
    "11a": {
        "vocab": [
            {"en": "get fit", "sr": "doći u formu"},
            {"en": "lose weight", "sr": "smršati"},
            {"en": "stop smoking", "sr": "prestati da pušim"},
            {"en": "move house", "sr": "preseliti se"},
            {"en": "have more fun", "sr": "više se zabavljati"},
            {"en": "do more exercise", "sr": "više vežbati"},
            {"en": "work less", "sr": "manje raditi"},
            {"en": "not eat sweet things", "sr": "ne jesti slatkiše"},
            {"en": "get a new job", "sr": "naći nov posao"},
            {"en": "have a holiday", "sr": "ići na odmor"},
            {"en": "do a computer course", "sr": "upisati kurs računara"},
            {"en": "make a New Year's resolution", "sr": "doneti novogodišnju odluku"},
        ],
        "phrases": [
            {"en": "I'm going to work less and have more fun.", "sr": "Manje ću da radim i više da se zabavljam."},
            {"en": "I'm going to have a holiday this year.", "sr": "Ove godine ću ići na odmor."},
            {"en": "I'm going to move to Australia.", "sr": "Selim se u Australiju."},
            {"en": "We're going to get fit.", "sr": "Doći ćemo u formu."},
            {"en": "Val's going to stop smoking.", "sr": "Val će da prestane da puši."},
            {"en": "I'm not going to eat sweet things any more.", "sr": "Više neću da jedem slatko."},
            {"en": "What are you going to do?", "sr": "Šta ćeš da radiš?"},
            {"en": "Where is she going to live?", "sr": "Gde će ona da živi?"},
        ],
        "grammar": [
            {"en": "be + going to + bazni glagol (planovi/odluke)", "sr": "buduća radnja koju smo isplanirali"},
            {"en": "I'm not going to … / They aren't going to …", "sr": "negacija"},
        ],
    },
    "11b": {
        "vocab": [
            {"en": "go to school / college / university", "sr": "ići u školu / koledž / na fakultet"},
            {"en": "leave school", "sr": "završiti školu"},
            {"en": "start a job", "sr": "početi posao"},
            {"en": "study for an exam", "sr": "učiti za ispit"},
            {"en": "revise for an exam", "sr": "ponavljati za ispit"},
            {"en": "take an exam", "sr": "polagati ispit"},
            {"en": "pass an exam ↔ fail an exam", "sr": "položiti ↔ pasti ispit"},
            {"en": "get some qualifications", "sr": "steći kvalifikacije"},
            {"en": "do a degree", "sr": "studirati za diplomu"},
            {"en": "a party / a film / a drink / a club", "sr": "žurka / film / piće / klub"},
            {"en": "a phone call / a concert / a meal / a job", "sr": "poziv / koncert / obrok / posao"},
        ],
        "phrases": [
            {"en": "Are you going to revise tonight?", "sr": "Hoćeš li večeras da ponavljaš?"},
            {"en": "Yes, I am. / No, I'm not.", "sr": "Da. / Ne."},
            {"en": "I might travel in the summer.", "sr": "Možda ću putovati leti."},
            {"en": "He's going to meet some friends this evening.", "sr": "Večeras će se naći sa drugarima."},
            {"en": "Eric couldn't answer the last three questions.", "sr": "Erik nije mogao da odgovori na poslednja tri pitanja."},
            {"en": "Jenny's going to phone her sister.", "sr": "Dženi će zvati sestru."},
        ],
        "grammar": [
            {"en": "going to = siguran plan; might = možda", "sr": "stepen izvesnosti"},
            {"en": "might + bazni glagol (bez to)", "sr": "I might go."},
        ],
    },
    "11c": {
        "vocab": [
            {"en": "turn right / turn left", "sr": "skreni desno / levo"},
            {"en": "go straight on", "sr": "idi pravo"},
            {"en": "go over the bridge", "sr": "pređi most"},
            {"en": "go past the pub", "sr": "prođi pored paba"},
            {"en": "go along this road / street", "sr": "idi tom ulicom"},
            {"en": "it's on the/your left", "sr": "sa leve strane je"},
            {"en": "it's on the/your right", "sr": "sa desne strane je"},
            {"en": "it's opposite", "sr": "preko puta je"},
            {"en": "it's next to", "sr": "pored je"},
            {"en": "a bridge / a corner / a car park", "sr": "most / ugao / parking"},
            {"en": "a bus station", "sr": "autobuska stanica"},
        ],
        "phrases": [
            {"en": "Excuse me, how do I get to …?", "sr": "Izvinite, kako da stignem do …?"},
            {"en": "Go along Abbott Street, past the bus station.", "sr": "Idite Abot ulicom, pored autobuske stanice."},
            {"en": "Then go over the bridge and turn right.", "sr": "Zatim pređite most i skrenite desno."},
            {"en": "It's the first house on the left.", "sr": "Prva kuća sa leve strane."},
            {"en": "It's next to a car park.", "sr": "Pored parkinga je."},
            {"en": "Thanks very much. — You're welcome.", "sr": "Hvala puno. — Nema na čemu."},
        ],
    },
    "11d": {
        "vocab": [
            {"en": "have a party / a wedding", "sr": "praviti žurku / venčanje"},
            {"en": "send an invitation", "sr": "poslati pozivnicu"},
            {"en": "book a flight / a hotel room", "sr": "rezervisati let / hotelsku sobu"},
            {"en": "rent a motorbike / a car", "sr": "iznajmiti motor / auto"},
            {"en": "get a taxi", "sr": "uzeti taksi"},
            {"en": "travel around (the country)", "sr": "putovati po zemlji"},
            {"en": "stay with someone", "sr": "biti kod nekoga (gost)"},
            {"en": "an aunt / an uncle / a cousin", "sr": "tetka / stric / rođak"},
            {"en": "an airport / public transport", "sr": "aerodrom / javni prevoz"},
        ],
        "phrases": [
            {"en": "Thank you very much for the invitation.", "sr": "Hvala vam mnogo na pozivu."},
            {"en": "Of course I'd love to come.", "sr": "Naravno, rado ću doći."},
            {"en": "Can I stay with you when I arrive?", "sr": "Mogu li da budem kod vas kad stignem?"},
            {"en": "If not, don't worry. I can book a hotel room.", "sr": "Ako ne može, ne brini. Rezervisaću sobu."},
            {"en": "I'd like to travel around after the wedding.", "sr": "Voleo bih da obiđem zemlju posle venčanja."},
            {"en": "Can I get to your place by public transport?", "sr": "Mogu li do vas javnim prevozom?"},
            {"en": "Lots of love, Mike", "sr": "Puno pozdrava, Majk (kraj prijateljskog mejla)"},
        ],
    },
    # =================================================================
    # UNIT 12
    # =================================================================
    "12a": {
        "vocab": [
            {"en": "0.2 = nought point two", "sr": "decimalna vrednost: 0,2"},
            {"en": "2.45 = two point four five", "sr": "2,45"},
            {"en": "127 = a hundred and twenty-seven", "sr": "127"},
            {"en": "2,300 = two thousand, three hundred", "sr": "2300"},
            {"en": "32,470 = thirty-two thousand, four hundred and seventy", "sr": "32 470"},
            {"en": "850,000 = eight hundred and fifty thousand", "sr": "850 000"},
            {"en": "1,000,000 = a million", "sr": "1 000 000"},
            {"en": "50,000,000 = fifty million", "sr": "50 000 000"},
            {"en": "a bowl / a chilli / heavy", "sr": "činija / čili / težak"},
            {"en": "cost / a haircut / a litre", "sr": "koštati / šišanje / litar"},
        ],
        "phrases": [
            {"en": "Sanjay taught the longest lesson in the world.", "sr": "Sandžej je održao najduži čas na svetu."},
            {"en": "It was 73 hours and 37 minutes long.", "sr": "Trajao je 73 sata i 37 minuta."},
            {"en": "They made the biggest bowl of soup.", "sr": "Napravili su najveću činiju supe."},
            {"en": "It was probably the world's hottest soup too.", "sr": "Verovatno i najljuća na svetu."},
            {"en": "It might not be the best burger in the world.", "sr": "Možda nije najbolji burger na svetu."},
            {"en": "She had the world's most expensive haircut.", "sr": "Imala je najskuplje šišanje na svetu."},
        ],
        "grammar": [
            {"en": "long → longest; big → biggest; easy → easiest", "sr": "Superlativ kratkih prideva: -est"},
            {"en": "expensive → the most expensive", "sr": "Duži pridevi: the most"},
            {"en": "good → the best; bad → the worst", "sr": "Nepravilni"},
            {"en": "the highest mountain / the best film", "sr": "the + superlativ + imenica"},
        ],
    },
    "12b": {
        "vocab": [
            {"en": "be → been", "sr": "biti → bio (PP)"},
            {"en": "cook → cooked", "sr": "kuvati → kuvao"},
            {"en": "go → been / gone", "sr": "ići → bio / otišao"},
            {"en": "have → had", "sr": "imati → imao"},
            {"en": "lose → lost", "sr": "izgubiti → izgubio"},
            {"en": "meet → met", "sr": "upoznati → upoznao"},
            {"en": "see → seen", "sr": "videti → video"},
            {"en": "stay → stayed", "sr": "ostati → ostao"},
            {"en": "study → studied", "sr": "učiti → učio"},
            {"en": "visit → visited", "sr": "posetiti → posetio"},
            {"en": "work → worked", "sr": "raditi → radio"},
            {"en": "write → written", "sr": "pisati → napisao"},
            {"en": "self-employed", "sr": "samostalan/preduzetnik"},
            {"en": "the Caribbean / the Prime Minister", "sr": "Karibi / premijer"},
        ],
        "phrases": [
            {"en": "I've been to about forty countries.", "sr": "Bio sam u oko 40 zemalja."},
            {"en": "I've stayed in some of the world's best hotels.", "sr": "Odsedao sam u najboljim hotelima na svetu."},
            {"en": "I haven't been to Australia.", "sr": "Nisam bio u Australiji."},
            {"en": "I've never tried sushi.", "sr": "Nikad nisam probao suši."},
            {"en": "Have you ever eaten Mexican food?", "sr": "Da li si ikad probao meksičku hranu?"},
            {"en": "Yes, I have. / No, I haven't.", "sr": "Da, jesam. / Ne, nisam."},
            {"en": "Two weeks ago I went to Mexico.", "sr": "Pre dve nedelje sam išao u Meksiko."},
        ],
        "grammar": [
            {"en": "have/has + past participle", "sr": "Present Perfect: I've gone, He's seen"},
            {"en": "ever (u pitanju), never (u negaciji)", "sr": "Have you ever … ? / I've never …"},
            {"en": "Present Perfect (kad nije rečeno) ↔ Past Simple (rečeno kada)", "sr": "kontrast"},
        ],
    },
    "12c": {
        "vocab": [
            {"en": "a passport", "sr": "pasoš"},
            {"en": "a boarding pass", "sr": "boarding pas"},
            {"en": "hand luggage", "sr": "ručni prtljag"},
            {"en": "a ticket", "sr": "karta"},
            {"en": "pack your bags", "sr": "spakovati torbe"},
            {"en": "passengers", "sr": "putnici"},
            {"en": "a flight number", "sr": "broj leta"},
            {"en": "a gate", "sr": "kapija (gate)"},
            {"en": "a check-in desk", "sr": "šalter za prijavu"},
            {"en": "a bag drop", "sr": "predaja prtljaga"},
            {"en": "a window / a middle / an aisle seat", "sr": "sedište do prozora / u sredini / do prolaza"},
            {"en": "on time ↔ delayed", "sr": "na vreme ↔ kasni"},
            {"en": "miss a plane", "sr": "propustiti avion"},
            {"en": "have a terrible journey", "sr": "imati užasno putovanje"},
        ],
        "phrases": [
            {"en": "Can I have your passport, please?", "sr": "Mogu li dobiti vaš pasoš?"},
            {"en": "How many bags are you checking in?", "sr": "Koliko torbi predajete?"},
            {"en": "Did you pack the bags yourself?", "sr": "Da li ste sami pakovali torbe?"},
            {"en": "You're in seat 16F.", "sr": "Sedite na 16F."},
            {"en": "Is the flight on time?", "sr": "Da li let kasni?"},
            {"en": "Yes, it is. Boarding is at 6:45.", "sr": "Da. Ukrcavanje je u 6.45."},
            {"en": "Enjoy your flight.", "sr": "Prijatan let."},
            {"en": "Have a safe trip!", "sr": "Srećan put!"},
            {"en": "Take care!", "sr": "Čuvaj se!"},
            {"en": "Keep in touch.", "sr": "Javljaj se."},
            {"en": "See you soon!", "sr": "Vidimo se uskoro!"},
            {"en": "Have you ever missed a plane?", "sr": "Jesi li ikad propustio avion?"},
        ],
    },
}
